
services:
  php:
    build:
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###
