<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260328154033 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE slot_unavailabilities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, blocked_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, slot_id INT NOT NULL, unavailability_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_84967B0A59E5119C ON slot_unavailabilities (slot_id)');
        $this->addSql('CREATE INDEX IDX_84967B0AF6922FEF ON slot_unavailabilities (unavailability_id)');
        $this->addSql('CREATE INDEX idx_slot_unavailability_slot_date ON slot_unavailabilities (slot_id, blocked_date)');
        $this->addSql('ALTER TABLE slot_unavailabilities ADD CONSTRAINT FK_84967B0A59E5119C FOREIGN KEY (slot_id) REFERENCES slots (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE slot_unavailabilities ADD CONSTRAINT FK_84967B0AF6922FEF FOREIGN KEY (unavailability_id) REFERENCES unavailabilities (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE slot_unavailabilities DROP CONSTRAINT FK_84967B0A59E5119C');
        $this->addSql('ALTER TABLE slot_unavailabilities DROP CONSTRAINT FK_84967B0AF6922FEF');
        $this->addSql('DROP TABLE slot_unavailabilities');
    }
}
