<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260405175537 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, calendar_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B5F1AFE5A40A2C8 ON activities (calendar_id)');
        $this->addSql('CREATE INDEX idx_activity_calendar_name ON activities (calendar_id, name)');
        $this->addSql('ALTER TABLE activities ADD CONSTRAINT FK_B5F1AFE5A40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendars (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendars DROP CONSTRAINT fk_84df820f19eb6921');
        $this->addSql('ALTER TABLE calendars ALTER client_id DROP NOT NULL');
        $this->addSql('ALTER TABLE calendars ADD CONSTRAINT FK_84DF820F19EB6921 FOREIGN KEY (client_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE slots ADD activity_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE slots ADD CONSTRAINT FK_C87435D081C06096 FOREIGN KEY (activity_id) REFERENCES activities (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_C87435D081C06096 ON slots (activity_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activities DROP CONSTRAINT FK_B5F1AFE5A40A2C8');
        $this->addSql('DROP TABLE activities');
        $this->addSql('ALTER TABLE calendars DROP CONSTRAINT FK_84DF820F19EB6921');
        $this->addSql('ALTER TABLE calendars ALTER client_id SET NOT NULL');
        $this->addSql('ALTER TABLE calendars ADD CONSTRAINT fk_84df820f19eb6921 FOREIGN KEY (client_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE slots DROP CONSTRAINT FK_C87435D081C06096');
        $this->addSql('DROP INDEX IDX_C87435D081C06096');
        $this->addSql('ALTER TABLE slots DROP activity_id');
    }
}
