<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315123902 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE booking_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, customer_name VARCHAR(255) NOT NULL, customer_email VARCHAR(255) NOT NULL, message TEXT DEFAULT NULL, status VARCHAR(10) DEFAULT \'pending\' CHECK (status IN (\'pending\', \'accepted\', \'declined\')), created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, slot_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_40B148DC59E5119C ON booking_requests (slot_id)');
        $this->addSql('CREATE TABLE calendars (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, display_mode VARCHAR(10) DEFAULT \'dayslot\' CHECK (display_mode IN (\'timeslot\', \'dayslot\')), public_token VARCHAR(36) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_id INT NOT NULL, agent_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_84DF820FAE981E3B ON calendars (public_token)');
        $this->addSql('CREATE INDEX IDX_84DF820F19EB6921 ON calendars (client_id)');
        $this->addSql('CREATE INDEX IDX_84DF820F3414710B ON calendars (agent_id)');
        $this->addSql('CREATE TABLE invitations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, token VARCHAR(36) NOT NULL, role VARCHAR(20) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, accepted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, invited_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_232710AE5F37A13B ON invitations (token)');
        $this->addSql('CREATE INDEX IDX_232710AEA7B4A7E3 ON invitations (invited_by_id)');
        $this->addSql('CREATE INDEX idx_invitation_token ON invitations (token)');
        $this->addSql('CREATE TABLE slots (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(5) CHECK (type IN (\'day\', \'time\')), start_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(10) DEFAULT \'open\' CHECK (status IN (\'open\', \'closed\', \'booked\', \'overridden\')), location VARCHAR(255) DEFAULT NULL, continent VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, calendar_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C87435D0A40A2C8 ON slots (calendar_id)');
        $this->addSql('CREATE INDEX idx_slot_calendar_start_status ON slots (calendar_id, start_at, status)');
        $this->addSql('CREATE TABLE unavailabilities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reason VARCHAR(255) DEFAULT NULL, calendar_id INT NOT NULL, client_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E08E40E4A40A2C8 ON unavailabilities (calendar_id)');
        $this->addSql('CREATE INDEX IDX_E08E40E419EB6921 ON unavailabilities (client_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, status VARCHAR(10) DEFAULT \'active\' CHECK (status IN (\'active\', \'blocked\')), name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, invited_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE INDEX IDX_1483A5E9A7B4A7E3 ON users (invited_by_id)');
        $this->addSql('ALTER TABLE booking_requests ADD CONSTRAINT FK_40B148DC59E5119C FOREIGN KEY (slot_id) REFERENCES slots (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendars ADD CONSTRAINT FK_84DF820F19EB6921 FOREIGN KEY (client_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendars ADD CONSTRAINT FK_84DF820F3414710B FOREIGN KEY (agent_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invitations ADD CONSTRAINT FK_232710AEA7B4A7E3 FOREIGN KEY (invited_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE slots ADD CONSTRAINT FK_C87435D0A40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendars (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE unavailabilities ADD CONSTRAINT FK_E08E40E4A40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendars (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE unavailabilities ADD CONSTRAINT FK_E08E40E419EB6921 FOREIGN KEY (client_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9A7B4A7E3 FOREIGN KEY (invited_by_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE booking_requests DROP CONSTRAINT FK_40B148DC59E5119C');
        $this->addSql('ALTER TABLE calendars DROP CONSTRAINT FK_84DF820F19EB6921');
        $this->addSql('ALTER TABLE calendars DROP CONSTRAINT FK_84DF820F3414710B');
        $this->addSql('ALTER TABLE invitations DROP CONSTRAINT FK_232710AEA7B4A7E3');
        $this->addSql('ALTER TABLE slots DROP CONSTRAINT FK_C87435D0A40A2C8');
        $this->addSql('ALTER TABLE unavailabilities DROP CONSTRAINT FK_E08E40E4A40A2C8');
        $this->addSql('ALTER TABLE unavailabilities DROP CONSTRAINT FK_E08E40E419EB6921');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E9A7B4A7E3');
        $this->addSql('DROP TABLE booking_requests');
        $this->addSql('DROP TABLE calendars');
        $this->addSql('DROP TABLE invitations');
        $this->addSql('DROP TABLE slots');
        $this->addSql('DROP TABLE unavailabilities');
        $this->addSql('DROP TABLE users');
    }
}
