<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315122221 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE calendars (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, display_mode VARCHAR(10) DEFAULT \'dayslot\' CHECK (display_mode IN (\'timeslot\', \'dayslot\')), public_token VARCHAR(36) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_id INT NOT NULL, agent_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_84DF820FAE981E3B ON calendars (public_token)');
        $this->addSql('CREATE INDEX IDX_84DF820F19EB6921 ON calendars (client_id)');
        $this->addSql('CREATE INDEX IDX_84DF820F3414710B ON calendars (agent_id)');
        $this->addSql('CREATE TABLE slots (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(5) CHECK (type IN (\'day\', \'time\')), start_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(10) DEFAULT \'open\' CHECK (status IN (\'open\', \'closed\', \'booked\', \'overridden\')), location VARCHAR(255) DEFAULT NULL, continent VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, calendar_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C87435D0A40A2C8 ON slots (calendar_id)');
        $this->addSql('CREATE INDEX idx_slot_calendar_start_status ON slots (calendar_id, start_at, status)');
        $this->addSql('ALTER TABLE calendars ADD CONSTRAINT FK_84DF820F19EB6921 FOREIGN KEY (client_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendars ADD CONSTRAINT FK_84DF820F3414710B FOREIGN KEY (agent_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE slots ADD CONSTRAINT FK_C87435D0A40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendars (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE slots DROP CONSTRAINT FK_C87435D0A40A2C8');
        $this->addSql('ALTER TABLE calendars DROP CONSTRAINT FK_84DF820F19EB6921');
        $this->addSql('ALTER TABLE calendars DROP CONSTRAINT FK_84DF820F3414710B');
        $this->addSql('DROP TABLE slots');
        $this->addSql('DROP TABLE calendars');
    }
}
