<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315123902 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE booking_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, customer_name VARCHAR(255) NOT NULL, customer_email VARCHAR(255) NOT NULL, message TEXT DEFAULT NULL, status VARCHAR(10) DEFAULT \'pending\' CHECK (status IN (\'pending\', \'accepted\', \'declined\')), created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, slot_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_40B148DC59E5119C ON booking_requests (slot_id)');
        $this->addSql('ALTER TABLE booking_requests ADD CONSTRAINT FK_40B148DC59E5119C FOREIGN KEY (slot_id) REFERENCES slots (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE booking_requests DROP CONSTRAINT FK_40B148DC59E5119C');
        $this->addSql('DROP TABLE booking_requests');
    }
}
