<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315122810 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE unavailabilities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reason VARCHAR(255) DEFAULT NULL, calendar_id INT NOT NULL, client_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E08E40E4A40A2C8 ON unavailabilities (calendar_id)');
        $this->addSql('CREATE INDEX IDX_E08E40E419EB6921 ON unavailabilities (client_id)');
        $this->addSql('ALTER TABLE unavailabilities ADD CONSTRAINT FK_E08E40E4A40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendars (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE unavailabilities ADD CONSTRAINT FK_E08E40E419EB6921 FOREIGN KEY (client_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE unavailabilities DROP CONSTRAINT FK_E08E40E4A40A2C8');
        $this->addSql('ALTER TABLE unavailabilities DROP CONSTRAINT FK_E08E40E419EB6921');
        $this->addSql('DROP TABLE unavailabilities');
    }
}
